Penggunaan perintah nltk.download("popular") akan mengunduh koleksi data yang sering digunakan dalam NLTK, termasuk korpus teks, model statistik, dan sumber daya lainnya yang berguna untuk tugas-tugas seperti tokenisasi, stemming, analisis sentimen, dan lainnya.

In [ ]:
import nltk
nltk.download("popular")
from nltk.tokenize import sent_tokenize, word_tokenize

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nlt

Melakukan Import Library yang akan digunakan pada program kali ini

In [ ]:
# Import library
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer
import requests
from bs4 import BeautifulSoup
from nltk.corpus import stopwords

import warnings
warnings.filterwarnings("ignore")

In [ ]:
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import numpy as np
lemmatizer = WordNetLemmatizer() ## Create object for lemmatizer

Memasukan tiga text ke dalam masing-masing variable yang mempunyai topik berbeda.

tiga variable tersebut digunakan untuk melakukan Training data dalam Model NLP nantinya.

In [ ]:
health_text = "The Hospital Incident Command System (HICS) has garnered increasing attention as a valuable organizational tool for effectively managing hospitals amidst the challenges posed by the COVID-19 pandemic. In our study, we focus on the implementation of HICS at the Isfahan province reference hospital, Isabn-e-Maryam, and delve into its performance during this critical period. Methodologically, we employed standard, open-ended interviews with key individuals occupying activated HICS leadership positions throughout the event to comprehensively document the actions taken during the pandemic. Additionally, we utilized a checklist derived from the job action sheets of HICS to assess performance systematically. The onset of the pandemic prompted the hospital director to revise the ICS structure, emphasizing a framework conducive to better control of COVID-19. Various strategies were considered to expand hospital inpatient capacity, thus facilitating surge capacity management. Notably, the highest performance score was observed in the realm of planning, indicating meticulous preparation and foresight in navigating the challenges posed by the pandemic. Performance in the Financial/Administration section was deemed intermediate, while other fields exhibited commendable performance levels. In our discussion, we underscore the significance of establishing HICS protocols tailored to the unique demands of the COVID-19 pandemic. Such measures not only enhance communication channels but also optimize resource allocation, ensure staff and patient safety, and sustain operational integrity. By integrating lessons learned from enduring events, hospitals can fortify their resilience and adaptability in confronting future crises effectively."

In [ ]:
sports_text = "Liverpool successfully fended off a late surge from Tottenham Hotspur in a thrilling encounter, where Mohamed Salah showcased his brilliance with two clinical strikes to secure a vital 2-1 victory for Jurgen Klopp's side. The match, held in north London, witnessed Liverpool's resurgence in the Premier League's top-four race following recent setbacks against Nottingham Forest and Leeds United. From the outset, Liverpool demonstrated their intent, swiftly taking the lead courtesy of Salah's expertly placed finish into the bottom corner just 11 minutes into the game. Although Tottenham showed glimpses of resurgence, including an Ivan Perisic header deflected onto the post and a penalty appeal waved away, Liverpool maintained their momentum. Moments before halftime, Eric Dier's unfortunate miscue gifted Salah another opportunity, which he capitalized on with a composed chip, notching his ninth goal in eight games. As the second half commenced, Tottenham emerged with renewed vigor, epitomized by Harry Kane's sublime strike in the 70th minute, assisted by substitute Dejan Kulusevski. Despite Rodrigo Bentancur and Kane threatening with headers, Liverpool's defense held firm, denying Tottenham's late surge. The victory marked Liverpools first away win in the Premier League this season, propelling them to eighth place and closing the gap to seven points behind fourth-placed Spurs, with a game in hand."

In [ ]:
finance_text = "Based on Fidelity's Financial Resolutions survey, it's clear that saving more money is a top priority for many individuals, with 43% of respondents expressing their intention to work towards this goal in the new year. Building a substantial nest egg offers numerous benefits, allowing individuals to finance major expenses such as purchasing a house, going on vacation, hosting a wedding, or acquiring high-ticket items without resorting to additional debt. Moreover, having savings provides a crucial safety net for unexpected emergency expenses. For those seeking to bolster their savings in the upcoming year, initiating the process with modest contributions can be incredibly effective. Even transferring as little as $10 per week into a savings account can lay the groundwork for cultivating a habit of saving. By starting small, individuals develop the discipline necessary for consistently setting aside funds. This habit becomes particularly advantageous when supplemented by salary increases, bonuses, or gift money, as individuals are already accustomed to prioritizing savings and are more inclined to allocate these additional funds accordingly. To further streamline the savings process and mitigate the risk of procrastination, automating transfers into a savings account is highly recommended. By setting up automatic transfers, individuals eliminate the need to actively make saving decisions, thereby minimizing the temptation to divert funds for discretionary spending. Most banks offer convenient options for scheduling automatic transfers directly through their mobile applications, making it simple to establish a consistent savings routine. For those keen on accelerating the growth of their savings, opting for a high-yield savings account presents a compelling opportunity. Unlike traditional savings accounts, high-yield savings accounts, such as the Marcus by Goldman Sachs Online Savings Account or the Ally Online Savings Account, offer more attractive interest rates, enabling savers to earn higher returns on their deposits each month. This heightened interest accumulation can significantly enhance the overall growth of savings over time, providing individuals with greater financial security and flexibility in achieving their long-term goals."

- Membuat variabel kosong bow_keys untuk menyimpan semua kata unik dari ketiga teks.

- Membuat variabel kosong corpus_texts untuk menyimpan teks-teks yang telah diproses.

ketiga text Sport, Health dan Finance akan dimasukan ke dalam satu variable yaitu 'texts'.
selanjutnya akan dilakukan iterasi pada 'texts' untuk melakukan proses sebagai berikut:

- Proses Tokenisasi kata-kata dalam 'texts'
- Proses Lemetisasi (menkonversi kata-kata kedalam bentuk dasar) dan menghapus (stopwords) dalam bahasa inggris

stopwords ini berisi daftar kata umum yang mempunyai fungsi tapi tidak mempunyai arti.

In [ ]:
texts = [health_text, sports_text, finance_text]
bow_keys = []
corpus_texts = []
for text in texts:
    words  = word_tokenize(text)
    texts = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    bow_keys += texts
    text = ' '.join(texts)
    corpus_texts.append(text)
bow_keys = set(bow_keys)
print(bow_keys)   #### Cleaned Data
print(corpus_texts)   #### Cleaned Data

{'prioritizing', 'prompted', 'realm', 'unexpected', 'brilliance', 'thus', 'open-ended', 'Financial', ',', 'showcased', 'placed', 'Hotspur', 'preparation', 'without', 'purchasing', 'north', 'emphasizing', 'Eric', 'implementation', 'adaptability', 'make', 'System', 'unique', 'year', 'establishing', 'priority', 'halftime', 'Incident', 'Liverpool', 'directly', 'eight', 'tool', 'conducive', 'incredibly', 'observed', 'action', 'Forest', 'section', 'bottom', 'activated', 'Leeds', 'demonstrated', 'valuable', 'making', 'revise', 'little', 'document', 'study', 'seven', 'fund', 'fortify', "'s", 'allocation', 'per', 'inpatient', 'challenge', 'taken', 'Perisic', 'significance', 'deflected', 'director', 'resurgence', 'miscue', 'respondent', 'Unlike', 'recent', 'throughout', 'gifted', 'place', 'sustain', 'commenced', 'channel', 'saving', 'resorting', 'operational', 'contribution', 'individual', 'COVID-19', 'interest', 'goal', 'initiating', 'Moreover', 'meticulous', 'Sachs', 'saver', 'point', '(', 'pr

- membuat text baru yaitu "new_text" yang masuk kedalam kategori olahraga.

- melakukan proses cleaning data pada "new_text" (Tokenisasi, lemetisasi, penghapusan stopwords)

- Memastikan kata-kata dalam new_text adalah bagian dari daftar kata-kata unik (bow_keys) yang telah dibuat sebelumnya.

- Menggunakan CountVectorizer dari scikit-learn untuk membuat representasi vektor dari teks yang telah dibersihkan. CountVectorizer menghitung frekuensi kemunculan kata-kata dalam setiap teks dan mengonversinya menjadi vektor.

- Mencetak panjang vektor pertama dalam array, yang mengindikasikan jumlah fitur (kata-kata unik) dalam representasi vektor tersebut.

In [ ]:
new_text = "Cristiano Ronaldo came off the bench to earn Manchester United a hard-fought 2-1 victory at Everton in the Premier League on Sunday, taking his career goal tally to 700 in the process. Just as United did last weekend in their derby mauling at the hands of local rivals Manchester City, they again found themselves behind early on at Goodison Park after Alex Iwobi curled a sublime strike into the net from 20 metres."

In [ ]:
query_words = word_tokenize(new_text)
query_words_clean = [lemmatizer.lemmatize(word) for word in query_words if word not in set(stopwords.words('english'))]
query_words_corpus = [word for word in query_words_clean if word in set(bow_keys)]
new_text_corpus = ' '.join(query_words_corpus)
corpus_texts.append(new_text_corpus)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer() ## Creating Object for CountVectorizer
bow_vectors = cv.fit_transform(corpus_texts).toarray()
print(bow_vectors)
print(len(bow_vectors[0]))

[[0 0 3 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 1 2 2]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
425


- melakukan normalisasi pada Bag Of Word yang sudah dikumpulkan, Normalisasi dilakukan dengan membagi setiap vektor oleh panjangnya (norma Euclidean)

  Normalisasi dilakukan untuk memastikan bahwa panjang vektor BoW tidak mempengaruhi perhitungan kemiripan antar teks.

- Menghitung kemiripan antara vektor normalisasi teks query (indeks ke-3 dalam bow_texts_norm) dengan vektor normalisasi dari setiap kategori (3 teks pertama dalam bow_texts_norm) menggunakan Dot Product.

- Mencari indeks dengan nilai kemiripan tertinggi dalam similarity_vector. lalu berdasarkan hasil nilai kemiripan maka akan dicetak hasil klasifikasi.

In [ ]:
# Normalize the BoW vectors
bow_texts_norm = []
for bow in bow_vectors:
  length = (sum(i*i for i in bow)) ** 0.5
  bow_norm = bow / length
  bow_texts_norm.append(bow_norm)

# Compute similarity using dot product
similarity_vector = []
bow_norm_query = bow_texts_norm[3]
for bow in bow_texts_norm[:3]:
  similarity_vector.append(sum(i*j for i,j in zip(bow,bow_norm_query)))
print(similarity_vector)

# Find the highest similarity
id_max_sim = similarity_vector.index(max(similarity_vector))
if (id_max_sim == 0):
  print ("The query text is classified as: Health")
elif (id_max_sim == 1):
  print ("The query text is classified as: Sport")
elif (id_max_sim == 2):
  print ("The query text is classified as: Finance")

[0.0, 0.24999999999999997, 0.06310547428675069]
The query text is classified as: Sport


#Penggunaan Function dalam Klasifikasi NLP

In [ ]:
def clean_text(text):
    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))
    words = word_tokenize(text)
    cleaned_words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return ' '.join(cleaned_words)

In [ ]:
def predict_topic(text_sport, text_medical, text_finance, query_data):
    clean_sport = clean_text(text_sport)
    clean_medical = clean_text(text_medical)
    clean_finance = clean_text(text_finance)

    corpus_texts = [clean_sport, clean_medical, clean_finance]

    corpus_texts.append(clean_text(query_data))

    cv = CountVectorizer()
    bow_vectors = cv.fit_transform(corpus_texts).toarray()

    bow_texts_norm = []
    for bow in bow_vectors:
        length = np.sqrt(np.sum(np.square(bow)))
        bow_norm = bow / length
        bow_texts_norm.append(bow_norm)

    similarity_vector = []
    bow_norm_query = bow_texts_norm[-1]  # Query data is the last element
    for bow in bow_texts_norm[:-1]:  # Exclude the query data
        similarity_vector.append(np.dot(bow, bow_norm_query))

    # Find the highest similarity
    id_max_sim = np.argmax(similarity_vector)
    if id_max_sim == 0:
        return "The query text is classified as: Sport"
    elif id_max_sim == 1:
        return "The query text is classified as: Medical"
    elif id_max_sim == 2:
        return "The query text is classified as: Finance"

In [ ]:
# Test your function!

# Training Data
text_sport = "Liverpool held off a late charge from Tottenham after Mohamed Salah struck twice to win 2-1 in north London and lift themselves back into the Premier League top-four race. Jurgen Klopp side had suffered shock defeats to relegation-threatened pair Nottingham Forest and Leeds in their last two league outings but started fast against Spurs, with a sharp touch and finish into the bottom corner from in-form Salah giving them the lead on 11 minutes. Ivan Perisic had a header deflected onto the post by Liverpool goalkeeper Alisson and Ryan Sessegnon saw a penalty shout from a challenge by Trent Alexander-Arnold waved away as Spurs came to life - but the Reds struck again just before the break thanks to a gift from Eric Dier. The centre-back miscued a header towards his own goal and Salah (40) raced through to chip in his ninth goal in eight games. Tottenham were sent out early for the second half and - not for the first time this season - were better after the break, with Alisson again pushing a Perisic effort onto the woodwork before Harry Kane (70) fired home a brilliant strike when played in by sub Dejan Kulusevski. Rodrigo Bentancur went close with a couple of headers and Kane glanced wide as Spurs desperately sought another late goal but Liverpool clung on for their first away win in the Premier League this season to move up to eighth and within seven points of fourth-placed Spurs, with a game in hand."
text_medical =  "There is growing popularity of the Hospital Incident Command System (HICS) as an organizational tool for hospital management in the COVID-19 pandemic. We specifically describe implementation of HICS at the Isfahan province reference hospital (Isabn-e-Maryam) during the COVID-19 pandemic and try to explore performance of it. Methods: To document the actions taken during the COVID-19 pandemic, standard, open-ended interviews were conducted with individuals occupying activated HICS leadership positions during the event. A checklist based on the job action sheets of the HICS was used for performance assessment. Results: With the onset of the pandemic, hospital director revised ICS structure that adheres to span of better control of COVID-19. Methods of expanding hospital inpatient capacity to enable surge capacity were considered. The highest performance score was in the field of planning. Performance was intermediate in Financial/Administration section and good in other fields. Discussion: In the current COVID-19 pandemic, establishing HICS with some consideration about long-standing events can help improve communication, resource use, staff and patient protection, and maintenance of roles."
text_finance = "According to Fidelity’s Financial Resolutions survey, saving more money was the number one-resolution for respondents. Close to half (43%) said this was a goal they wanted to work toward in the new year. Building a nest egg can help you pay for big ticket items — like a house, a vacation, a wedding or even just an expensive item you really want — without taking on additional debt. Having savings can also come in handy if an emergency expense comes up. If you’re looking to increase your savings in the new year, it helps to start small — even if you’re only transferring $10 a week into your savings account. Starting small helps you build a muscle for saving. This way, when you receive salary bumps, bonuses and gift money, you’ve already gotten into the habit of saving, and you’ll be more likely to transfer that money to your savings account. You may also want to consider automating that process instead of just manually moving money into your savings. Relying on manual transfers leaves a lot of room for procrastination — and before we know it, we’ve spent the money we intended to save. But when you set up automatic transfers into your savings account, you take away the need to make that decision altogether. You can usually schedule automatic transfers through your bank’s mobile app. Lastly, if you want to see your savings grow just a little faster, you can opt for a high-yield savings account instead of a traditional savings account. High-yield savings accounts — like the Marcus by Goldman Sachs Online Savings Account or the Ally Online Savings Account — pay you more in interest each month compared to traditional savings accounts."

# Testing Data
query_data = """Cristiano Ronaldo came off the bench to earn Manchester United a hard-fought 2-1 victory at Everton in the Premier League on Sunday, taking his career goal tally to 700 in the process. Just as United did last weekend in their derby mauling at the hands of local rivals Manchester City, they again found themselves behind early on at Goodison Park after Alex Iwobi curled a sublime strike into the net from 20 metres."""

In [ ]:
predict_topic(text_sport, text_medical, text_finance, query_data)

'The query text is classified as: Sport'